repos:
  - repo: victormgomes/laravel-query-engine
  - repo: victormgomes/async-api

settings:
  delete_branch_on_merge: true
  squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
